### ISSUE TITLE
macOS Sierra/Xcode 8 problem with /usr/bin/security 

### ISSUE THREAD

**Issue by santey** [bitrise-io/steps-certificate-and-profile-installer#20]
When i run /usr/bin/security cms -D -i /path/to/provision
at first it prints security: SecPolicySetValue: One or more parameters passed to a function were not valid.

Thats why next step /usr/libexec/PlistBuddy -c 'Print UUID' crashes

**Comment by viktorbenei** [comment]
Thanks for reporting!

This is a known Sierra issue, we'll try to implement a workaround for this step ASAP!

**Comment by godrei** [comment]
Hi @santey ,
new version [1.8.0](https://github.com/bitrise-io/steps-certificate-and-profile-installer/releases/tag/1.8.0) is available in the steplib with fix for this issue.
