### ISSUE TITLE
SecKeychainItemImport: MAC verification failed

### ISSUE THREAD

**Issue by danialmoghaddam** [bitrise-io/steps-certificate-and-profile-installer#23]
version: 1.8.1

All default variables

Error: 
`=> Installing downloaded certificate`
`Command failed, output: security: SecKeychainItemImport: MAC verification failed during PKCS12 import (wrong password?)
Command failed, err: exit status 1`

**Comment by viktorbenei** [comment]
This issue is usually happens if you specify an invalid password.

If that's not the case, please include the full build log

**Comment by danialmoghaddam** [comment]
Ohhh yes, my bad. Sorry

**Comment by ctaggart** [comment]
I tried using a blank password and got this error. Once I set a password, it worked.

**Comment by viktorbenei** [comment]
@ctaggart without the logs it's impossible to tell what the issue was. Can you please fill out a issue report at https://discuss.bitrise.io/c/issues , including the related build's bitrise.io URL? That would help a lot to be able to help you asap! :)

**Comment by ctaggart** [comment]
Thanks @viktorbenei. If I need help, I'll submit an issue report there. Simply using a password is good enough for me right now.

**Comment by viktorbenei** [comment]
All right, thanks @ctaggart ! :)

**Comment by mohit-sentieo** [comment]
I am getting this error when my password is blank. Did you reexport the certificate with a password ?

**Comment by bitce** [comment]
Hi @mohit-sentieo  indeed that's what you'd need to do to get around this error!
