### ISSUE TITLE
[Question] Working directory path as 'Certificate URL'.

### ISSUE THREAD

**Issue by SergeyKovalenko** [bitrise-io/steps-certificate-and-profile-installer#9]
Is it possible to specify file path within working directory for 'Certificate URL' instead of web URL? I 'd like to store my mobileprovision in the repository and then use it for signing.  In this case I don't need to upload it to bitrise each time when the new devis is added to mobileprovision.

**Comment by godrei** [comment]
You can sepcify both of the certificate_url and provisioning_profile_url whit your local url (file://YOUR/PATH) as well. 
BITRISE_SOURCE_DIR refers to your current working directory on bitrise, by default the folder where your project is cloned. The latest version (1.3.0) of the step, only deals with full paths, so you can refer to your profile as “file://$BITRISE_SOURCE_DIR/MY/PROFILE”. 
Today we will release a new version of the step, the update includes the relative path handling, so in the new version you can use simply “file://.//MY/PROFILE".

**Comment by SergeyKovalenko** [comment]
Awesome. Thank you a lot. You are doing a great job !!!

**Comment by viktorbenei** [comment]
Thanks, the new version will be out soon, we'll let you know here and then close this issue :)

**Comment by viktorbenei** [comment]
Version `1.4.0` was just released, relative file path is mentioned in the changelogs: https://github.com/bitrise-io/steps-certificate-and-profile-installer/releases/tag/1.4.0

Thanks for your feedback @SergeyKovalenko !

**Comment by bitrise-adam** [comment]
Hi there @Rishabhios 

You can see all the releases and the changes that were part of the release at https://github.com/bitrise-io/steps-certificate-and-profile-installer/releases/
